#!/usr/bin/env bash
# create a temporary working copy of the hosts file
HOSTS='/etc/hosts'

#backup
cp $HOSTS ${HOSTS}.bak

#remove existing ips
sed -i '/^127\.0\.0\.1[[:space:]]\+localhost/d' $HOSTS
sed -i '/^127\.0\.0\.2[[:space:]]\+localhost/d' $HOSTS

# Add required localhost mapping
echo "127.0.0.2    localhost" >> $HOSTS

# Remove old facebook.com entries
sed -i '/facebook\.com/d' $HOSTS

# Add required facebook.com mapping
echo "8.8.8.8      facebook.com" >> $HOSTS
